SELECT CodEmpresa,
  CodFilial,
  CodCobrancaDigital,
  BloqueioKey,
  Origem,
  CodOrigem,
  Situacao,
  CodCliente,
  NomeCliente,
  CNPJ_CPF,
  Telefone,
  Email,
  Endereco,
  Numero,
  Complemento,
  Bairro,
  CEP,
  CodigoMunicipio,
  NomeMunicipio,
  UFMunicipio,
  CodUsuario,
  NomeUsuario,
  EstacaoTrabalho,
  Ip
FROM integracao.CobrancaDigital