SELECT CodLiberacaoBloqueio,
  Item,
  Status,
  CodRegra,
  Regra,
  MensagemBloqueio,
  DescricaoBloqueio,
  ObservacaoBloqueio,
  DataHoraSolicitacao,
  CodUsuarioSolicitacao,
  NomeUsuarioSolicitacao,
  EstacaoTrabalhoSolicitacao,
  ObservacaoLiberacaoBloqueio,
  MotivoRejeicaoLiberacaoBloqueio
FROM ItemLiberacaoBloqueio