SELECT CodEmpresa,
  CodConferir,
  Item,
  SessionId,
  Situacao,
  CodCarrinhoPercurso,
  ItemCarrinhoPercurso,
  CodConferente,
  NomeConferente,
  DataConferencia,
  HoraConferencia,
  CodProduto,
  CodUnidadeMedida,
  Quantidade
FROM Expedicao.ItemConferencia