SELECT CodEmpresa,
  CodConferir,
  Origem,
  CodOrigem,
  CodPrioridade,
  Situacao,
  Data,
  Hora,
  Historico,
  Observacao,
  CodMotivoCancelamento,
  DataCancelamento,
  HoraCancelamento,
  CodUsuarioCancelamento,
  NomeUsuarioCancelamento,
  ObservacaoCancelamento
FROM Expedicao.Conferir