SELECT CodEmpresa,
  CodSepararEstoque,
  Item,
  SessionId,
  Situacao,
  CodCarrinhoPercurso,
  ItemCarrinhoPercurso,
  CodSeparador,
  NomeSeparador,
  DataSeparacao,
  HoraSeparacao,
  CodProduto,
  CodUnidadeMedida,
  Quantidade
FROM Expedicao.ItemSeparacaoEstoque
