INSERT INTO Expedicao.TipoOperacaoExpedicao(
    CodEmpresa,
    CodTipoOperacaoExpedicao,
    Descricao,
    Ativo,
    Tipo,
    CodSetorConferencia,
    CodPrioridade,
    CodRelatorio,
    CodLocalArmazenagem,
    MovimentaEstoque,
    CodTipoMovimentoEstoque,
    FazerConferencia,
    FazerArmazenamento,
    ControlaLote,
    ControlaNumeroSerie
  )
VALUES (
    @CodEmpresa,
    @CodTipoOperacaoExpedicao,
    @Descricao,
    @Ativo,
    @Tipo,
    @CodSetorConferencia,
    @CodPrioridade,
    @CodRelatorio,
    @CodLocalArmazenagem,
    @MovimentaEstoque,
    @CodTipoMovimentoEstoque,
    @FazerConferencia,
    @FazerArmazenamento,
    @ControlaLote,
    @ControlaNumeroSerie
  )
